version: '2'
services:
  php:
    build: ./php-fpm
    volumes:
      - .:/var/www/html
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
#    depends_on:
#      - mysql
#  web:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - .:/var/www/html
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - php
#  mysql:
#    image: mysql:5.6
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - "3333:3306"
